FROM node:latest

WORKDIR /home

ENTRYPOINT [ "npm" ]

# docker-compose run npm команда

# docker-compose run npm install 

# docker-compose run --rm -p 5173:5173 npm run dev -- --host  # при разработке
# docker-compose run --rm npm run build  # сборка