FROM composer:latest

WORKDIR /home/laravel

ENTRYPOINT [ "composer" ]

# docker-compose run composer команда

# docker-compose run --remove-orphans composer create-project laravel/laravel . 
# создаст каталог src и установит Learavel (src изначально долженотсутствовать!!!)