version: "3.8"

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root             # пароль для базы данных (логин по умолчанию root)
      MYSQL_DATABASE: laravel        # имя базы данных

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 9095:80                             # 9095 - порт по к-рому доступен phpMyAdmin вне контейнера (т.е. http://localhost:9095 )
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db    
    
  composer:
    build:
      context: composer
      dockerfile: Dockerfile
    volumes:
      - ../src:/home/laravel
    environment:
      - APACHE_RUN_USER=#1000
      - COMPOSER_MEMORY_LIMIT=-1
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root    

  npm:
    build:
      context: npm
      dockerfile: Dockerfile
    volumes:
      - ../src:/home

  artisan:
    build:
      context: artisan
      dockerfile: Dockerfile
    volumes:
      - ../src:/home
    environment:
      - APACHE_RUN_USER=#1000
      - COMPOSER_MEMORY_LIMIT=-1
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root  
